name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Instalar dependências (SDL2)
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Compilando os arquivos C (sem linkar)
      run: |
        # Este script agora usa a flag -c para apenas compilar e verificar a sintaxe,
        # gerando arquivos .o (objetos) em vez de executáveis.
        # Isso garante que todo o seu código está sintaticamente correto.
        find . -type f -name "*.c" -print0 | while IFS= read -r -d $'\0' file; do
          OBJECT_FILE="${file%.c}.o"
          
          if [[ "$file" == *"aula12/estrelas.c"* ]]; then
            echo "Compilando (com SDL2): $file -> $OBJECT_FILE"
            gcc -c "$file" -o "$OBJECT_FILE" $(sdl2-config --cflags --libs) -lm
          else
            echo "Compilando: $file -> $OBJECT_FILE"
            gcc -c "$file" -o "$OBJECT_FILE" -lm
          fi
        done
